# -*- coding: utf-8 -*-
"""Delete Samples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1or8nC41VkB6PoqK2YwVBUeJ7TWS_IdGD
"""

!pip install chromadb

import random
import chromadb
import os

from google.colab import drive
drive.mount('/content/drive')

def delete_ids_that_from_file(db_path, collection_name, input_file="deleted_ids.txt"):
    """
    Reads IDs from a file and deletes them from a specified collection.

    Args:
        db_path (str): Path to the Chroma DB database.
        collection_name (str): Name of the collection to modify.
        input_file (str): Path to the file containing IDs to delete.
    """
    # Step 1: Ensure the file exists
    if not os.path.exists(input_file):
        print(f"File {input_file} does not exist.")
        return

    # Step 2: Load the IDs from the file
    with open(input_file, "r") as file:
        ids_to_delete = file.read().splitlines()

    if not ids_to_delete:
        print("No IDs found in the file to delete.")
        return

    print(f"Loaded {len(ids_to_delete)} IDs from {input_file}.")

    # Step 3: Load the Chroma DB client using PersistentClient with the correct path
    client = chromadb.PersistentClient(path=db_path)

    # Step 4: Retrieve the collection
    collection = client.get_collection(collection_name)
    # Step 3: Get all document IDs from the collection by fetching all documents
    all_indices = collection.get(ids=None)  # This retrieves all documents, including their IDs
    document_ids = all_indices['ids']  # Extract document IDs

    # Count the number of documents before deletion
    initial_count = len(document_ids)
    print(f"Initial number of documents: {initial_count}")


    # Step 5: Delete the IDs from the collection
    for doc_id in ids_to_delete:
        collection.delete(ids=[doc_id])

    print(f"Deleted {len(ids_to_delete)} IDs from the collection '{collection_name}'.")

     # Step 7: Count the number of documents after deletion
    all_indices_after_deletion = collection.get(ids=None)  # Fetch remaining documents
    remaining_document_ids = all_indices_after_deletion['ids']
    remaining_count = len(remaining_document_ids)

    print(f"Remaining number of documents: {remaining_count}")

db_path = "/content/drive/MyDrive/All DB/Code/grapg/Python_VDB_Graph_Code_BERT"

client_py = chromadb.PersistentClient(path=db_path)

collections = client_py.list_collections()

collections

"""# comparison"""

# Step 4: Retrieve the collection

client = chromadb.PersistentClient(path="/content/drive/MyDrive/All DB/Code/grapg/Java_Script_VDB_Graph_Code_Bert")
collection = client.get_collection("CODEJSCRIPT")
# Step 3: Get all document IDs from the collection by fetching all documents
all_indices = collection.get(ids=None)  # This retrieves all documents, including their IDs
document_ids = all_indices['ids']  # Extract document IDs

# Step 4: Retrieve the collection

client2 = chromadb.PersistentClient(path="/content/drive/MyDrive/All DB/Code/javascript_codet5_code_Vdb")
collection2 = client2.get_collection("javascript_codet5_code_collection")
# Step 3: Get all document IDs from the collection by fetching all documents
all_indices2 = collection2.get(ids=None)  # This retrieves all documents, including their IDs
document_ids2 = all_indices2['ids']  # Extract document IDs

unique_to_document_ids = set(document_ids) - set(document_ids2)
print(len(unique_to_document_ids))
print(unique_to_document_ids)

common_ids = set(document_ids) & set(document_ids2)
print(len(common_ids))

"""# graph code bert"""

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/grapg/C++_VDB_Graph_Code_Bert",
    collection_name="codeC"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/grapg/Java_Script_VDB_Graph_Code_Bert",
    collection_name="CODEJSCRIPT"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/grapg/Java_VDB_Graph_Code_Bert",
    collection_name="CODEJAVA"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/grapg/Python_VDB_Graph_Code_BERT",
    collection_name="codePY"
)

import chromadb

def delete_id0_Graph_Code_Bert(db_path, collection_name):
    # Initialize the PersistentClient and connect to the database
    client = chromadb.PersistentClient(path=db_path)

    # Retrieve the collection
    collection = client.get_collection(collection_name)

    # Delete the document with the specific ID '0'
    collection.delete(ids=['0'])

    # Step 3: Get all document IDs from the collection by fetching all documents
    all_indices = collection.get(ids=None)  # This retrieves all documents, including their IDs
    document_ids = all_indices['ids']  # Extract document IDs
    print("remain",len(document_ids))

    print(f"Deleted document with ID '0' from collection '{collection_name}' in database '{db_path}'")

delete_id0_Graph_Code_Bert(
    db_path="/content/drive/MyDrive/All DB/Code/grapg/C++_VDB_Graph_Code_Bert",
    collection_name="codeC"
)

delete_id0_Graph_Code_Bert(
    db_path="/content/drive/MyDrive/All DB/Code/grapg/Java_Script_VDB_Graph_Code_Bert",
    collection_name="CODEJSCRIPT"
)

delete_id0_Graph_Code_Bert(
    db_path="/content/drive/MyDrive/All DB/Code/grapg/Java_VDB_Graph_Code_Bert",
    collection_name="CODEJAVA"
)

delete_id0_Graph_Code_Bert(
    db_path="/content/drive/MyDrive/All DB/Code/grapg/Python_VDB_Graph_Code_BERT",
    collection_name="codePY"
)

"""# code"""

# delete_ids_that_from_file(
#     db_path="/content/drive/MyDrive/All DB/Code/C++_VDB_Graph_Code_Bert",
#     collection_name="codeC"
# )

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/C_codet5_code_Vdb",
    collection_name="C_codet5_code_collection"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/JAVA-qween-VectorDB",
    collection_name="Java-VectorDataBase-Qwen2.5-Coder-7B"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/JavaScript-qween-VectorDB",
    collection_name="JavaScript-VectorDataBase-Qwen2.5-Coder-7B"
)

# delete_ids_that_from_file(
#     db_path="/content/drive/MyDrive/All DB/Code/Java_Script_VDB_Graph_Code_Bert",
#     collection_name="CODEJSCRIPT"
# )

# delete_ids_that_from_file(
#     db_path="/content/drive/MyDrive/All DB/Code/Java_VDB_Graph_Code_Bert",
#     collection_name="CODEJAVA"
# )

# delete_ids_that_from_file(
#     db_path="/content/drive/MyDrive/All DB/Code/Python_VDB_Graph_Code_BERT",
#     collection_name="codePY"
# )

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/c++-qwen-VectorDB",
    collection_name="CVectorDataBase-Qwen2.5-Coder-7B"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/java_codet5_code_Vdb",
    collection_name="java_codet5_code_collection"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/javascript_codet5_code_Vdb",
    collection_name="javascript_codet5_code_collection"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/python-qwen-VectorDB",
    collection_name="pythonVectorDataBase-Qwen2.5-Coder-7B"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Code/python_codet5_code_Vdb",
    collection_name="python_codet5_code_collection"
)

"""# desc"""

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Desc/C_codet5_disc_Vdb",
    collection_name="C_codet5_disc_collection"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Desc/Chroma_DB_JavaScript_Desc_falcon",
    collection_name="JavaScript-VectorDB-Desc-Falcon"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Desc/Chroma_DB_Java_Desc_falcon",
    collection_name="Java-VectorDB-Desc-Falcon"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Desc/Chroma_DB_Py_Desc_falcon",
    collection_name="Python-VectorDB-Desc-Falcon"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Desc/chroma_db_c_desc_falcon",
    collection_name="C-VectorDB-Desc-Falcon"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Desc/java_codet5_disc_Vdb",
    collection_name="java_codet5_disc_collection"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Desc/javascript_codet5_disc_Vdb",
    collection_name="javascript_codet5_disc_collection"
)

delete_ids_that_from_file(
    db_path="/content/drive/MyDrive/All DB/Desc/python_codet5_disc_Vdb",
    collection_name="python_codet5_disc_collection"
)